"""first step

Revision ID: 680b55e2b3b8
Revises: c1c670b8ebc4
Create Date: 2020-11-26 11:53:24.914624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680b55e2b3b8'
down_revision = 'c1c670b8ebc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'university',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('students_number', sa.Integer(), nullable=True),
        sa.Column('engine', sa.String(), nullable=True),
        sa.Column('engine_parameters', sa.JSON(), nullable=True),
        sa.Column('structure', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_university'))
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_action_comment_action_type'), 'action_type', ['comment'], ['id'])
        batch_op.drop_column('action_type')

    with op.batch_alter_table('timer', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_timer_id_user'), 'user', ['id'], ['user_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_group', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('university', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_data', sa.JSON(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_university_university'), 'university', ['university'], ['id'])
        batch_op.drop_column('user_type')

    op.drop_table('user_type')
    op.drop_table('schedule_chache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_university_university'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_type', ['user_type'], ['id'])
        batch_op.drop_column('user_data')
        batch_op.drop_column('university')
        batch_op.drop_column('is_group')
        batch_op.drop_column('is_banned')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_timer_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_action_comment_action_type'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'action_type', ['action_type'], ['id'])

    op.create_table(
        'schedule_chache',
        sa.Column('schedule_id', sa.INTEGER(), nullable=False),
        sa.Column('date', sa.INTEGER(), nullable=False),
        sa.Column('schedule_text', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('schedule_id', 'date')
    )
    op.create_table(
        'user_type',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('type', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('university')
    # ### end Alembic commands ###
